{% set name = "AirTrafficSim" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim/releases/download/{{ version }}/AirTrafficSim-{{ version }}.tar.gz
  url: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim/archive/v{{ version }}.tar.gz
  sha256: 649a0b2809163d65b7f95c1a8485d38ae7c6f2b9f3b88d61a5a88f225c04789c
  # Command to get sha256
  # curl -sL https://github.com/HKUST-OCTAD-LAB/AirTrafficSim/archive/v0.0.0.tar.gz | openssl sha256

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - "airtrafficsim = airtrafficsim.__main__:main"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - Flask
    - Flask-SocketIO
    - Eventlet
    - cartopy
    - cdsapi
    - xarray
    - openap

test:
  imports:
    - airtrafficsim
  requires:
    - pip

about:
  home: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim
  summary: 'A web-based air traffic simulation software written in Python and javascript.'
  description: |
    AirTrafficSim is a web-based air traffic simulation software written in Python and javascript. 
    It is designed to visualize historical and research data, perform microscopic studies of air traffic movement with the integration of a historical weather database, and evaluate the performance of ATM algorithms.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://hkust-octad-lab.github.io/AirTrafficSim/

extra:
  recipe-maintainers:
    - kyfrankie
